name: "goal_dqn"
trainer_type: "offpolicy"
is_actor_critic: false
learning_rate: 1e-3

hyperparams:
  is_double: true
  discount_factor: 0.99
  estimation_step: 1
  target_update_freq: 0
  reward_normalization: false
  clip_loss_grad: false
