base:
  name: "FrozenLake-v1"
  render_mode: "rgb_array"
  # remove the holes
  desc: [
    "SFFF",
    "FFFF",
    "FFFF",
    "FFFG"
  ]
  # no slipping
  is_slippery: false

dream:
  min_nsteps: 1000
  max_nsteps: 10000

vec:
  # making these two values different creates problems with SubprocVectorEnv
  num_envs: 1
  num_dream_envs: 1 