base:
  name: "FrozenLake-v1"
  render_mode: "rgb_array"

dream:
  min_nsteps: 1000
  max_nsteps: 10000

vec:
  num_envs: 5
  # TODO making these two values different creates problems with SubprocVectorEnv
  num_dream_envs: 5