is_goal_aware: true

buffers:
  train_buf_size: 20
  test_buf_size: 20

training:
  max_epoch: 3
  step_per_epoch: 50
  step_per_collect: 20
  episode_per_test: 1
  batch_size: 5
  repeat_per_collect: 1