is_goal_aware: true

environment:
  name: "FrozenLake-v1"
  num_train_envs: 5
  num_test_envs: 5

buffers:
  train_buf_size: 500
  test_buf_size: 1

algorithm:
  name: "ppo_based"
  learning_rate: 3e-4

training:
  max_epoch: 20
  step_per_epoch: 1000
  step_per_collect: 100
  episode_per_test: 5
  batch_size: 32
  repeat_per_collect: 1

logging:
  log_path: "logs/frozenlake_goal"