use_kb: true
save_kb: true
is_goal_aware: true

buffers:
  train_buf_size: 5000
  test_buf_size: 1
  kb_size: 1000

  dream_train_buf_size: 500

training:
  real:
    max_epoch: 10
    step_per_epoch: 1000
    step_per_collect: 100
    episode_per_test: 1
    batch_size: 32
    repeat_per_collect: 1
  dream:
    max_epoch: 2
    step_per_epoch: 200
    step_per_collect: 50
    # this needs to be defined to comply with Tianshou's API, even though we do not test in the dream
    episode_per_test: 1
    batch_size: 16
    repeat_per_collect: 1