use_kb: false
save_kb: false

buffers:
  train_buf_size: 1000
  test_buf_size: 1

training:
  real:
    max_epoch: 10
    step_per_epoch: 100
    step_per_collect: 10
    episode_per_test: 1
    batch_size: 64
