is_goal_aware: true

buffers:
  train_buf_size: 500
  test_buf_size: 1
  kb_size: 1000

  dream_train_buf_size: 100

training:
  real:
    max_epoch: 20
    step_per_epoch: 1000
    step_per_collect: 100
    episode_per_test: 5
    batch_size: 32
    repeat_per_collect: 1
  dream:
    max_epoch: 5
    step_per_epoch: 1000
    step_per_collect: 100
    # this needs to be defined to comply with Tianshou's API, even though we do not test in the dream
    episode_per_test: 1
    batch_size: 31
    repeat_per_collect: 1